# Generated by Django 4.2.7 on 2023-11-14 18:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('allbooks', '0004_remove_chapter_content_remove_chapter_order_text_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='text',
            name='chapter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='text', to='allbooks.chapter'),
        ),
    ]
