# Generated by Django 4.2.7 on 2023-11-14 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allbooks', '0005_alter_text_chapter'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='description',
            field=models.TextField(default=''),  # Add a default value
            preserve_default=False,
        ),
    #     migrations.AddField(
    #         model_name='collection',
    #         name='description',
    #         field=models.TextField(default=None),
    #         preserve_default=False,
    #     ),
    
        migrations.AddField(
            model_name='collection',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='collection_images/'),
        ),
    ]
