# Generated by Django 4.2.7 on 2023-11-14 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allbooks', '0006_collection_description_collection_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='description',
            field=models.TextField(default=''),
        ),
    ]
