# Generated by Django 4.2.7 on 2023-11-20 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allbooks', '0008_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='group_readings',
            field=models.ManyToManyField(blank=True, related_name='group_readings', to='allbooks.book'),
        ),
    ]
