# Generated by Django 4.2.7 on 2023-11-21 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allbooks', '0009_userprofile_group_readings'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='source_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
